name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar Docker Compose
        run: |
          docker compose version || (
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
          )

      - name: Estabelecer conexão SSH com VPS
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Verificar e fazer deploy na VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} '
            set -e

            PROJECT_DIR="/home/ubuntu/devtools/n8n"

            # Verifica se o diretório existe
            if [ ! -d "$PROJECT_DIR/.git" ]; then
              echo "Repositório não encontrado, clonando..."
              git clone git@github.com:leograva/n8n.git $PROJECT_DIR
            fi

            cd $PROJECT_DIR
            echo "Fazendo pull do código..."
            git pull origin main

            echo "Atualizando containers..."
            docker compose pull
            docker compose up -d --build
          '
